name: .NET Azure Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  # Specify your .NET version here

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}  # Set this environment variable in your GitHub repo settings
        slot-name: 'production'  # Optional: Add if deploying to a specific slot
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Set this secret in your GitHub repo settings
        package: ./publish

    - name: Cleanup after build
      if: always()
      run: rm -rf ./publish

    - name: Analyze with CodeQL  # Optional: Add CodeQL Analysis
      uses: github/codeql-action/init@v3
      with:
        languages: 'csharp'  # Specify languages here

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
